src/main/java/org/opentosca/csarrepo/service/ShowCsarFileService.java
src/main/java/org/opentosca/csarrepo/servlet/CsarFileDetailsServlet.java
src/main/webapp/csardetailsservlet.ftl
src/main/webapp/csarfiledetailsservlet.ftl

create show csarFileService and corresponding gui, fix #141

---

src/main/java/org/opentosca/csarrepo/filesystem/FileSystem.java

implemented hash functionality in filesystem, refs #151

---

src/main/java/org/opentosca/csarrepo/filesystem/FileSystem.java
src/main/java/org/opentosca/csarrepo/model/repository/FileSystemRepository.java
src/main/java/org/opentosca/csarrepo/service/DeleteCsarFileService.java

extended deleteCsarFileService for deleting files from db and fs, refs #133

---

src/main/java/org/opentosca/csarrepo/rest/resource/CsarResource.java

add delete csar to REST, fix #123

---

src/main/java/org/opentosca/csarrepo/service/DeleteCsarService.java

deleteCsar service handels not existing csar correctly, fix #156

---

src/main/java/org/opentosca/csarrepo/service/ShowCsarService.java

handling of not existing csar in showCsarService, fix #155

---

src/main/java/org/opentosca/csarrepo/filesystem/FileSystem.java
src/main/java/org/opentosca/csarrepo/model/CsarFile.java
src/main/java/org/opentosca/csarrepo/rest/model/CsarFileEntry.java
src/main/java/org/opentosca/csarrepo/service/UploadCsarFileService.java

* moved UUID generation into saveToFileSystem function
* changed version from type string to long
* getResult in UploadCsarFileService returns CsarFile
#143

Streamline/Refactor Access to Files, refs #143

---

src/main/java/org/opentosca/csarrepo/service/DownloadCsarFileService.java
src/main/java/org/opentosca/csarrepo/servlet/DownloadCsarFileServlet.java

renamed DownloadCsarService to DownloadCsarFileService, refs #163

---

src/main/java/org/opentosca/csarrepo/filesystem/FileSystem.java
src/main/java/org/opentosca/csarrepo/model/HashedFile.java
src/main/java/org/opentosca/csarrepo/rest/model/CsarFileEntry.java
src/main/java/org/opentosca/csarrepo/rest/resource/CsarFileResource.java
src/main/java/org/opentosca/csarrepo/service/DeleteCsarFileService.java
src/main/java/org/opentosca/csarrepo/service/UploadCsarFileService.java

removed .csar file extension and lowercased filename, refs #121

---

src/main/webapp/csardetailsservlet.ftl

filename changed from fileName to filename

Fixing filename (from fileName to filename) for template csardetailsservlet.ftl

---

.gitignore
src/main/java/org/opentosca/csarrepo/filesystem/FileSystem.java
src/main/java/org/opentosca/csarrepo/util/RepositoryProperties.java
src/main/webapp/WEB-INF/repository.properties.example

* .gitignore
* add custom properties file
* repository.properties.example
* example properties file
* RepositoryProperties.java
* reader for custom property file
#168

move storagepath for csarfiles to properties, fix #168

---

src/main/java/org/opentosca/csarrepo/rest/resource/CsarResource.java

add upload file for REST refs #121

add upload file for REST refs #121

---

src/main/java/org/opentosca/csarrepo/filesystem/FileSystem.java
src/main/java/org/opentosca/csarrepo/model/HashedFile.java
src/main/java/org/opentosca/csarrepo/rest/model/CsarFileEntry.java
src/main/java/org/opentosca/csarrepo/rest/resource/CsarFileResource.java
src/main/java/org/opentosca/csarrepo/service/DeleteCsarFileService.java
src/main/java/org/opentosca/csarrepo/service/DownloadCsarFileService.java
src/main/java/org/opentosca/csarrepo/service/UploadCsarFileService.java
src/main/java/org/opentosca/csarrepo/servlet/DownloadCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/util/DownloadCsarFileObject.java
src/main/webapp/csardetailsservlet.ftl

Consistent file extension handling, refs #170

---

src/main/java/org/opentosca/csarrepo/model/Csar.java
src/main/java/org/opentosca/csarrepo/model/User.java
src/main/java/org/opentosca/csarrepo/model/WineryServer.java
src/main/resources/hibernate.cfg.xml

implemented winery server model, refs #166

---

src/main/java/org/opentosca/csarrepo/servlet/LoginServlet.java
src/main/webapp/login.ftl

added login maske, refs #174

---

src/main/webapp/login.ftl

removed comment, refs #174

---

src/main/java/org/opentosca/csarrepo/model/WineryServer.java

changed from InetSocketAddress to URI

---

src/main/java/org/opentosca/csarrepo/model/repository/UserRepository.java

implemented user repository, refs #200

---

src/main/java/org/opentosca/csarrepo/model/repository/WineryServerRepository.java

implement WineryServerRepository, fix #203

---

src/main/java/org/opentosca/csarrepo/service/CreateUserService.java

implemented CreateUserService, refs #177

---

src/main/java/org/opentosca/csarrepo/service/LoadUserService.java

implemented load user service, refs #178

---

src/main/java/org/opentosca/csarrepo/rest/resource/CsarFileResource.java

CsarFileResource now uses DownloadService instead of accessing the filesystem directly

mod CsarFileResource to use DownloadService #172

---

src/main/java/org/opentosca/csarrepo/service/CreateWineryServerService.java

add createWineryServerService, fix #199

---

src/main/java/org/opentosca/csarrepo/service/ListWineryServerService.java

add ListWineryServerService, fix #188

---

src/main/java/org/opentosca/csarrepo/service/ListOpenToscaServerService.java

create ListOpenToscaServerService refs #186

create ListOpenToscaServerService refs #186

---

src/main/java/org/opentosca/csarrepo/service/ShowOpenToscaServerService.java

add ShowOpenToscaServerService refs #185

add ShowOpenToscaServerService refs #185

---

src/main/java/org/opentosca/csarrepo/servlet/CreateCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CreateWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListWineryServerServlet.java
src/main/webapp/layout.ftl
src/main/webapp/listWineryServerServlet.ftl

implement manage winery view + create winery, fix #183

---

src/main/java/org/opentosca/csarrepo/service/CreateOpenToscaServerService.java
src/main/java/org/opentosca/csarrepo/service/ShowOpenToscaServerService.java
src/main/java/org/opentosca/csarrepo/servlet/CreateOpenToscaServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListOpenToscaServerServlet.java
src/main/webapp/layout.ftl
src/main/webapp/listOpenToscaServerServlet.ftl

add new OpenTOSCA view with working creation and viewing of OpenTosca Servers ref #180

add manageOpenTOSCA View ref #180

---

src/main/java/org/opentosca/csarrepo/service/DeleteWineryServerService.java
src/main/java/org/opentosca/csarrepo/service/ShowWineryServerService.java
src/main/java/org/opentosca/csarrepo/service/UpdateWineryServerService.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/UpdateWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/WineryServerDetailsServlet.java
src/main/webapp/wineryServerDetailsServlet.ftl

implement view for wineryserverdetail, edit, delete, fix #184 fix #187

---

src/main/java/org/opentosca/csarrepo/servlet/CsarFileDetailsServlet.java
src/main/webapp/csarfiledetailsservlet.ftl
src/main/webapp/listWineryServerServlet.ftl

This is not a fix, but it wouldn't harm to merge it into master (better for other things depending on it ... e.g. REST Connector to ContainerAPI)

add GUI elements for OT Deployment ref #147

---

src/main/java/org/opentosca/csarrepo/service/DeleteOpenToscaServerService.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteOpenToscaServerServlet.java

add servlet, service to delete OTServers refs #220

add servlet, service to delete OTServers refs #220

---

src/main/java/org/opentosca/csarrepo/model/OpenToscaServer.java
src/main/java/org/opentosca/csarrepo/model/User.java
src/main/java/org/opentosca/csarrepo/model/WineryServer.java
src/main/java/org/opentosca/csarrepo/model/join/OpenToscaServerUser.java
src/main/java/org/opentosca/csarrepo/model/join/UserWineryServer.java
src/main/java/org/opentosca/csarrepo/service/CreateOpenToscaServerService.java
src/main/resources/hibernate.cfg.xml

implemented join tables for user, refs #213

---

src/main/java/org/opentosca/csarrepo/servlet/DeployCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/util/ContainerApiClient.java
src/main/webapp/csarfiledetailsservlet.ftl

add working deployment on OT Container refs #223

add working deployment on OT Container refs #223

---

src/main/java/org/opentosca/csarrepo/model/CloudInstance.java
src/main/java/org/opentosca/csarrepo/model/OpenToscaServer.java

implemented cloud instance mapping, refs #213

---

src/main/java/org/opentosca/csarrepo/model/CloudInstance.java
src/main/java/org/opentosca/csarrepo/model/Csar.java
src/main/java/org/opentosca/csarrepo/model/CsarFile.java
src/main/java/org/opentosca/csarrepo/model/HashedFile.java
src/main/java/org/opentosca/csarrepo/model/OpenToscaServer.java
src/main/java/org/opentosca/csarrepo/model/User.java
src/main/java/org/opentosca/csarrepo/model/WineryServer.java

"cannot simultaneously fetch multiple bags"

fixed jpa eager bug

---

src/main/java/org/opentosca/csarrepo/model/repository/FileSystemRepository.java
src/main/java/org/opentosca/csarrepo/servlet/CsarFileDetailsServlet.java
src/main/webapp/csardetailsservlet.ftl
src/main/webapp/csarfiledetailsservlet.ftl

Extended CSAR File Details view to show list of related cloud instances

CSAR File Details View #147

---

src/main/java/org/opentosca/csarrepo/service/ListUserService.java

added ListUserService, refs #179

---

src/main/java/org/opentosca/csarrepo/servlet/ListUserServlet.java
src/main/webapp/layout.ftl
src/main/webapp/listUserServlet.ftl

added list user page, #176

---

src/main/webapp/listOpenToscaServerServlet.ftl

fixes yellow error message :wink: 
Model now contains Users instead of User
but this will need additional work therefore the User was just removed instead

remove column 'owner' from OTServerView refs #241

---

src/main/java/org/opentosca/csarrepo/servlet/LogoutServlet.java

implemented logout servlet, refs #248

---

src/main/java/org/opentosca/csarrepo/servlet/CreateCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CreateOpenToscaServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CreateWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CsarDetailsServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CsarFileDetailsServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DashboardServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteOpenToscaServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeployCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DownloadCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListOpenToscaServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/UpdateWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/UploadCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/servlet/WineryServerDetailsServlet.java

added ui authentication to each servlet, refs #251

---

src/main/java/org/opentosca/csarrepo/servlet/AbstractServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CreateCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CsarDetailsServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CsarFileDetailsServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DashboardServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListOpenToscaServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListUserServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/LoginServlet.java
src/main/java/org/opentosca/csarrepo/servlet/WineryServerDetailsServlet.java
src/main/webapp/layout.ftl

implemented error notifications in ui, refs #182

---

src/main/java/org/opentosca/csarrepo/service/ExportToWineryService.java
src/main/java/org/opentosca/csarrepo/servlet/CsarFileDetailsServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ExportToWineryServlet.java
src/main/java/org/opentosca/csarrepo/util/WineryApiClient.java
src/main/webapp/csarfiledetailsservlet.ftl

implement push to winery, fix #238

---

src/main/java/org/opentosca/csarrepo/servlet/OpenToscaServerDetailsServlet.java
src/main/webapp/OpenToscaServerDetailsServlet.ftl
src/test/java/org/opentosca/csarrepo/model/repository/OpenToscaRepositoryTest.java

*add testcase for creation of an opentosca server
*add some unlock functionality to the opentosca ftl
*update OpenToscaServlet to match the changes

add opentoscaServer detailview refs #181

---

src/main/java/org/opentosca/csarrepo/model/CloudInstance.java
src/main/java/org/opentosca/csarrepo/model/CsarFile.java

added csarfile 1-n cloudinstance relationship, refs #262

---

src/main/java/org/opentosca/csarrepo/service/UpdateOpenToscaServerService.java
src/main/java/org/opentosca/csarrepo/servlet/UpdateOpenToscaServerServlet.java

add update for openToscaServer, fix #225

---

src/main/java/org/opentosca/csarrepo/service/ExportToWineryService.java
src/main/java/org/opentosca/csarrepo/servlet/AbstractServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CreateCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CreateOpenToscaServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CreateWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CsarDetailsServlet.java
src/main/java/org/opentosca/csarrepo/servlet/CsarFileDetailsServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteOpenToscaServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeployCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DownloadCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ExportToWineryServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListOpenToscaServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListUserServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/LoginServlet.java
src/main/java/org/opentosca/csarrepo/servlet/OpenToscaServerDetailsServlet.java
src/main/java/org/opentosca/csarrepo/servlet/UpdateOpenToscaServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/UpdateWineryServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/UploadCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/servlet/WineryServerDetailsServlet.java
src/main/java/org/opentosca/csarrepo/util/ContainerApiClient.java
src/main/java/org/opentosca/csarrepo/util/StringUtils.java
src/test/java/org/opentosca/csarrepo/model/repository/StringUtilsTest.java

Re-did and fixed the commits, well this time it should be better :octopus:

fix error handling inside servlets refs #266

---

src/main/java/org/opentosca/csarrepo/model/Csar.java

added namespace and service template id, refs #277

---

src/main/java/org/opentosca/csarrepo/servlet/AbstractServlet.java
src/main/java/org/opentosca/csarrepo/servlet/LoginServlet.java
src/main/webapp/layout.ftl

implemented success notification, refs #273

---

src/main/java/org/opentosca/csarrepo/exception/DeploymentException.java
src/main/java/org/opentosca/csarrepo/model/CsarFile.java
src/main/java/org/opentosca/csarrepo/model/join/CsarFileOpenToscaServer.java
src/main/java/org/opentosca/csarrepo/service/DeployToOpenToscaService.java
src/main/java/org/opentosca/csarrepo/servlet/CsarFileDetailsServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeployCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/util/ContainerApiClient.java
src/main/webapp/csarfiledetailsservlet.ftl

*extend model of CsarFileOpenToscaServer to save a location
*extend model of CsarFile to set location upon adding a OpenToscaServer
*create a service which handles deployment to OT
*create DeploymentException which is used for deployment failures
*adjust csarfiledetailsservlet.ftl to show new relations

add storage of meta-data for opentosca deployment refs #283

---

src/main/java/org/opentosca/csarrepo/model/CsarFile.java
src/main/java/org/opentosca/csarrepo/model/repository/JoinRepository.java
src/main/java/org/opentosca/csarrepo/service/UndeployCsarFileOpenToscaService.java
src/main/java/org/opentosca/csarrepo/servlet/UndeployCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/util/ContainerApiClient.java
src/main/webapp/csarfiledetailsservlet.ftl

* add undeployCsarFile meta data operations

add mapping repo #289

---

src/main/java/org/opentosca/csarrepo/model/repository/JoinRepository.java
src/main/java/org/opentosca/csarrepo/service/UndeployCsarFileOpenToscaService.java
src/main/java/org/opentosca/csarrepo/servlet/UndeployCsarFileOpenToscaServlet.java
src/main/java/org/opentosca/csarrepo/util/ContainerApiClient.java
src/main/webapp/csarfiledetailsservlet.ftl

*create joinRepo to get Relation between OpenToscaServer and CsarFile
*renamed UndeployCsarFileServlet to match ServiceName
*GUI changes inside csarfiledetailsservlet.ftl

add delete operation for Container Client fix #285

---

src/main/java/org/opentosca/csarrepo/service/UploadCsarFileService.java
src/main/java/org/opentosca/csarrepo/util/Extractor.java

Implemented extractor and extracted data from tosca.meta, refs #291

---

src/main/java/org/opentosca/csarrepo/service/UploadCsarFileService.java
src/main/java/org/opentosca/csarrepo/util/Extractor.java

implemented check for namespace and servicetemplate id, refs #278

---

src/main/java/org/opentosca/csarrepo/service/CreateUserService.java
src/main/java/org/opentosca/csarrepo/service/EditCsarNameService.java
src/main/java/org/opentosca/csarrepo/servlet/AbstractServlet.java
src/main/java/org/opentosca/csarrepo/servlet/EditCsarNameServlet.java
src/main/java/org/opentosca/csarrepo/util/StringUtils.java
src/main/webapp/csardetailsservlet.ftl
src/main/webapp/listCsarServlet.ftl
src/main/webapp/login.ftl
src/test/java/org/opentosca/csarrepo/model/repository/RenameCsarTest.java
src/test/java/org/opentosca/csarrepo/model/repository/UserRepositoryTest.java

This implementation uses some javascript functionalities for the interaction between servlet and user:
* A javascript prompt askes the user for a new name
* A hidden field form will be submitted to the servlet
* The servlet gets the data via the form
* The servlet updates the data in the DB
In the CreateUserService was the userId missing, so I added it afterwards.

Implemented renaming Csars, refs #298

---

src/main/java/org/opentosca/csarrepo/model/repository/CsarRepository.java
src/main/java/org/opentosca/csarrepo/service/UploadCsarFileService.java

implemented counting version, refs #297

---

src/main/webapp/csarDetailsServlet.ftl

added csar delete button, refs #300

---

pom.xml
src/main/java/org/opentosca/csarrepo/service/AbstractService.java
src/main/java/org/opentosca/csarrepo/service/ImportCsarFromWineryService.java
src/main/java/org/opentosca/csarrepo/service/WineryServicetemplateListService.java
src/main/java/org/opentosca/csarrepo/servlet/CsarDetailsServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ImportCsarFileFromWineryServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ImportCsarFromWineryServlet.java
src/main/java/org/opentosca/csarrepo/servlet/ListCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/NewVersionFromWineryServlet.java
src/main/java/org/opentosca/csarrepo/servlet/WineryServerDetailsServlet.java
src/main/java/org/opentosca/csarrepo/util/Servicetemplate.java
src/main/java/org/opentosca/csarrepo/util/WineryApiClient.java
src/main/webapp/csarDetailsServlet.ftl
src/main/webapp/csardetailsservlet.ftl
src/main/webapp/listCsarServlet.ftl
src/main/webapp/newVersionFromWinery.ftl
src/main/webapp/wineryServerDetailsServlet.ftl

import csar from winery, fix #275

---

src/main/webapp/csarDetailsServlet.ftl
src/main/webapp/csarFileDetailsServlet.ftl
src/main/webapp/listOpenToscaServerServlet.ftl
src/main/webapp/listUserServlet.ftl
src/main/webapp/openToscaServerDetailsServlet.ftl

* all delete buttons are in detail view
* all delete buttons use bootstrap confirmation pop ups
#320

consistent delete buttons, fix #320

---

src/main/java/org/opentosca/csarrepo/servlet/DeleteCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteCsarServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteOpenToscaServerServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteUserServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeleteWineryServerServlet.java

flash messages appear for a successful delete for:
* csar
* csarFile
* user
* openToscaServer
* wineryServer
#323

add success messages, fix #323

---

src/main/webapp/csarDetailsServlet.ftl

Changed detail icon from icon to label "Details", refs #324

---

src/main/java/org/opentosca/csarrepo/servlet/CsarDetailsServlet.java

fix not existing csar leads to white page, fix #327

---

src/main/java/org/opentosca/csarrepo/model/repository/CsarRepository.java

getBynamespaceAndServicetemplate for CsarRepo, fix #335

---

src/main/java/org/opentosca/csarrepo/service/ExportToWineryService.java
src/main/java/org/opentosca/csarrepo/servlet/ExportToWineryServlet.java
src/main/java/org/opentosca/csarrepo/util/WineryApiClient.java

better errors for failed winery export, fix #270

---

src/main/java/org/opentosca/csarrepo/service/CreateWineryServerService.java
src/main/java/org/opentosca/csarrepo/servlet/WineryServerDetailsServlet.java
src/main/webapp/wineryServerDetailsServlet.ftl

moved logic Nik101010 293

---

src/main/java/org/opentosca/csarrepo/service/ListLivedataOpenToscaCsarService.java
src/main/java/org/opentosca/csarrepo/service/ListLivedataOpenToscaInstancesService.java
src/main/java/org/opentosca/csarrepo/util/ContainerApiClient.java
src/main/java/org/opentosca/csarrepo/util/jaxb/DeployedCsars.java
src/main/java/org/opentosca/csarrepo/util/jaxb/ServiceInstanceList.java
src/main/java/org/opentosca/csarrepo/util/jaxb/SimpleXLink.java
src/main/java/org/opentosca/csarrepo/util/jaxb2/References.java
src/test/java/org/opentosca/csarrepo/util/ContainerApiClientTest.java

This functionality will be needed to display the deployed csars.

implemented getDeployedCsars service, refs #302

---

src/main/webapp/listOpenToscaServerServlet.ftl
src/main/webapp/listWineryServerServlet.ftl

converted url to link, refs #321

---

src/main/java/org/opentosca/csarrepo/servlet/OpenToscaServerDetailsServlet.java
src/main/webapp/openToscaServerDetailsServlet.ftl

Implemented displaying of deployed CSARs refs #302

---

src/main/java/org/opentosca/csarrepo/model/Csar.java
src/main/java/org/opentosca/csarrepo/model/CsarPlan.java
src/main/java/org/opentosca/csarrepo/model/HashedFile.java
src/main/java/org/opentosca/csarrepo/model/Plan.java
src/main/java/org/opentosca/csarrepo/model/repository/CsarPlanRepository.java
src/main/java/org/opentosca/csarrepo/service/DeployToOpenToscaService.java
src/main/java/org/opentosca/csarrepo/service/DownloadCsarFileService.java
src/main/java/org/opentosca/csarrepo/service/UploadCsarFileService.java
src/main/java/org/opentosca/csarrepo/servlet/AbstractServlet.java
src/main/java/org/opentosca/csarrepo/servlet/DeployCsarFileServlet.java
src/main/java/org/opentosca/csarrepo/util/ContainerApiClient.java
src/main/java/org/opentosca/csarrepo/util/PlanInvocationHelper.java
src/main/java/org/opentosca/csarrepo/util/StringUtils.java
src/main/resources/hibernate.cfg.xml
src/main/webapp/openToscaServerDetailsServlet.ftl

This has many WIPs (identified by todos inside the source)
All this changes are related to #301.

init the planInvocation branch

---

src/main/java/org/opentosca/csarrepo/util/PlanInvocationHelper.java
src/main/webapp/openToscaServerDetailsServlet.ftl

small fixes to integrate the new way of getting a reference to our internal csarFiles

fix getting plans from OT

---

src/main/java/org/opentosca/csarrepo/util/jaxb/ServiceInstanceEntry.java
src/main/webapp/livedataOpenToscaServerInstances.ftl
src/main/webapp/openToscaServerDetailsServlet.ftl

* added link to ContainerAPI in general
* ServiceInstanceIDs now link to ContainerAPI

add OTDetailsView: references to ContainerAPI fixes #360

---

src/main/java/org/opentosca/csarrepo/servlet/LivedataWineryServerTemplatesServlet.java
src/main/java/org/opentosca/csarrepo/servlet/WineryServerDetailsServlet.java
src/main/webapp/livedataWineryServerTemplates.ftl
src/main/webapp/wineryServerDetailsServlet.ftl

load service templates asynchronously, fixes #363

---

pom.xml
src/main/resources/hibernate.cfg.xml

switched ConnectionPool implementation to C3P0 instead of Hibernate default implementation

switch connection pool driver fix #365

---

src/main/java/org/opentosca/csarrepo/servlet/CsarFileDetailsServlet.java
src/main/webapp/csarDetailsServlet.ftl
src/main/webapp/csarFileDetailsServlet.ftl
src/main/webapp/listCsarServlet.ftl
src/main/webapp/listOpenToscaServerServlet.ftl
src/main/webapp/listUserServlet.ftl
src/main/webapp/listWineryServerServlet.ftl
src/main/webapp/openToscaServerDetailsServlet.ftl
src/main/webapp/wineryServerDetailsServlet.ftl

GUI consistency, fix #272

---

src/main/java/org/opentosca/csarrepo/servlet/LivedataOpenToscaInstancesServlet.java
src/main/webapp/livedataOpenToscaServerCsars.ftl
src/main/webapp/livedataOpenToscaServerInstances.ftl

Implemented listing of management plans, refs #334

---

src/main/java/org/opentosca/csarrepo/model/repository/CsarFileRepository.java
src/main/java/org/opentosca/csarrepo/model/repository/CsarPlanRepository.java
src/main/java/org/opentosca/csarrepo/model/repository/CsarRepository.java
src/main/java/org/opentosca/csarrepo/model/repository/FileSystemRepository.java
src/main/java/org/opentosca/csarrepo/model/repository/JoinRepository.java
src/main/java/org/opentosca/csarrepo/model/repository/OpenToscaServerRepository.java
src/main/java/org/opentosca/csarrepo/model/repository/UserRepository.java
src/main/java/org/opentosca/csarrepo/model/repository/WineryServerRepository.java
src/main/java/org/opentosca/csarrepo/service/CountCsarFileService.java
src/main/java/org/opentosca/csarrepo/service/CountCsarPlanService.java
src/main/java/org/opentosca/csarrepo/service/CountCsarService.java
src/main/java/org/opentosca/csarrepo/service/CountDeployedCsarService.java
src/main/java/org/opentosca/csarrepo/service/CountHashedFileService.java
src/main/java/org/opentosca/csarrepo/service/CountOpenToscaServerService.java
src/main/java/org/opentosca/csarrepo/service/CountUserService.java
src/main/java/org/opentosca/csarrepo/service/CountWineryServerService.java
src/main/java/org/opentosca/csarrepo/servlet/DashboardServlet.java
src/main/webapp/dashboard.ftl

Dashboard, fix #315

---

src/main/java/org/opentosca/csarrepo/service/LivedataOpenToscaCsarService.java
src/main/java/org/opentosca/csarrepo/servlet/LivedataOpenToscaCsarsServlet.java
src/main/java/org/opentosca/csarrepo/util/DeployedCsarObject.java
src/main/java/org/opentosca/csarrepo/util/PlanInvocationHelper.java
src/main/webapp/livedataOpenToscaServerCsars.ftl

opentoscaserver livedata only shows csars deployed from the repository, #378

---

src/main/java/org/opentosca/csarrepo/servlet/LivedataOpenToscaCsarsServlet.java
src/main/webapp/livedataOpenToscaServerCsars.ftl

add link to vinothek in csar livedata, fix #380
